name: Test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make dist
      - uses: ./.github/actions/test
        with:
          distribution: "./h3-dist.zip"
