name: Test

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install lark-parser
      - run: rm docs/api.md
      - run: make docs/api.md
      - run: git diff --exit-code docs

  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, i386]
    steps:
      - uses: actions/checkout@v2
      - name: Login to repository
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "$GITHUB_ACTOR" --password-stdin
      - name: Test
        run: docker run -v ${PWD}:/github/workspace docker.pkg.github.com/bytesandbrains/h3-pg/test:${{ matrix.arch }}
